### ISSUE TITLE
update-overall-stats cron endpoint cannot run in Vercel 

### ISSUE THREAD

**Issue by PabloCastellano** [Blobscan/blobscan#151]
This endpoint requires access to the beacon node.

Proposal: Instead of publicly exposing the beacon node to the Internet

1. Move this functionality from the web to the api component which has already access to the beacon node
2. Run the cronjob in blobscan's vm

Logs from vercel-cron:

```
❌ Invalid environment variables: { BEACON_NODE_ENDPOINT: [ 'Required' ] }
Error: Invalid environment variables
    at T.m (file:///var/task/node_modules/@t3-oss/env-nextjs/dist/index.mjs:1:500)
    at T (file:///var/task/node_modules/@t3-oss/env-nextjs/dist/index.mjs:1:690)
    at P (file:///var/task/node_modules/@t3-oss/env-nextjs/dist/index.mjs:1:1081)
    at /var/task/apps/web/.next/server/pages/api/cron/update-overall-stats.js:200:74
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
RequestId: 4134a094-73f5-42bb-8160-090a4dd05812 Error: Runtime exited without providing a reason
Runtime.ExitError
```

**Comment by PabloCastellano** [comment]
Done

**Comment by YongZL** [comment]
hello,I also have the same problem, how to solve it?
