### ISSUE TITLE
Create a custom page for http 404 and 500 errors

### ISSUE THREAD

**Issue by PJColombo** [Blobscan/blobscan#66]
[example](https://blobscan.com/search?q=0x8f90b7793272e0a59a8890197f6b1c1c14ba76fcbdfa139241a2ff4ddf504fce9c45c84fbcc3f0ce666c748159b57a39)

![image](https://github.com/user-attachments/assets/6829a987-13d6-48da-aa12-b0f26d0b7c54)

**Comment by PabloCastellano** [comment]
Dunno if related but I found this error today in vercel logs, mentioning a 500.html not found file:

The link that caused this error was [a simple search](https://blobscan.com/search?q=0x8f90b7793272e0a59a8890197f6b1c1c14ba76fcbdfa139241a2ff4ddf504fce9c45c84fbcc3f0ce666c748159b57a39).

```
ching cause stack trace ...
    at createRetryer (file:///var/task/node_modules/@tanstack/query-core/build/lib/retryer.mjs:149:5) {
  code: 'INTERNAL_SERVER_ERROR',
  name: 'TRPCError',
  page: '/search',
  [cause]: TypeError: Cannot read properties of undefined (reading 'url')
      at buildURL (/var/task/apps/web/.next/server/pages/search.js:985:24)
      at /var/task/apps/web/.next/server/pages/search.js:992:17
      at callRecursive (file:///var/task/node_modules/@trpc/server/dist/index.mjs:456:38)
      at resolve (file:///var/task/node_modules/@trpc/server/dist/index.mjs:486:30)
      at callProcedure (file:///var/task/node_modules/@trpc/server/dist/config-00ffd309.mjs:181:12)
      at Object.query (file:///var/task/node_modules/@trpc/react-query/dist/server/index.mjs:20:28)
      at Object.queryFn (file:///var/task/node_modules/@trpc/react-query/dist/server/index.mjs:58:39)
      at Object.fetchFn [as fn] (file:///var/task/node_modules/@tanstack/query-core/build/lib/query.mjs:252:27)
      at run (file:///var/task/node_modules/@tanstack/query-core/build/lib/retryer.mjs:101:31)
      at createRetryer (file:///var/task/node_modules/@tanstack/query-core/build/lib/retryer.mjs:149:5)
}
MissingStaticPage [Error]: Failed to load static file for page: /500 ENOENT: no such file or directory, open '/var/task/apps/web/.next/server/pages/500.html'
    at /var/task/node_modules/next/dist/server/require.js:109:19
    at async loadComponentsImpl (/var/task/node_modules/next/dist/server/load-components.js:80:26)
    at async NextNodeServer.findPageComponentsImpl (/var/task/node_modules/next/dist/server/next-server.js:439:36)
    at async NextNodeServer.renderErrorToResponseImpl (/var/task/node_modules/next/dist/server/base-server.js:1651:30)
    at async pipe.req.req (/var/task/node_modules/next/dist/server/base-server.js:1591:30)
    at async NextNodeServer.pipeImpl (/var/task/node_modules/next/dist/server/base-server.js:735:25)
    at async NextNodeServer.handleCatchallRenderRequest (/var/task/node_modules/next/dist/server/next-server.js:729:17)
    at async NextNodeServer.runImpl (/var/task/node_modules/next/dist/server/base-server.js:720:9)
    at async NextNodeServer.handleRequestImpl (/var/task/node_modules/next/dist/server/base-server.js:668:20)
TypeError: Cannot read properties of undefined (reading 'url')
    at buildURL (/var/task/apps/web/.next/server/pages/search.js:985:24)
    ... 8 lines matching cause stack trace ...
    at createRetryer (file:///var/task/node_modules/@tanstack/query-core/build/lib/retryer.mjs:149:5) {
  code: 'INTERNAL_SERVER_ERROR',
  name: 'TRPCError',
  page: '/search',
  [cause]: TypeError: Cannot read properties of undefined (reading 'url')
      at buildURL (/var/task/apps/web/.next/server/pages/search.js:985:24)
      at /var/task/apps/web/.next/server/pages/search.js:992:17
      at callRecursive (file:///var/task/node_modules/@trpc/server/dist/index.mjs:456:38)
      at resolve (file:///var/task/node_modules/@trpc/server/dist/index.mjs:486:30)
      at callProcedure (file:///var/task/node_modules/@trpc/server/dist/config-00ffd309.mjs:181:12)
      at Object.query (file:///var/task/node_modules/@trpc/react-query/dist/server/index.mjs:20:28)
      at Object.queryFn (file:///var/task/node_modules/@trpc/react-query/dist/server/index.mjs:58:39)
      at Object.fetchFn [as fn] (file:///var/task/node_modules/@tanstack/query-core/build/lib/query.mjs:252:27)
      at run (file:///var/task/node_modules/@tanstack/query-core/build/lib/retryer.mjs:101:31)
      at createRetryer (file:///var/task/node_modules/@tanstack/query-core/build/lib/retryer.mjs:149:5)
}
Error: Runtime exited without providing a reason
```
